### ISSUE TITLE
css实现宽度自适应，高度为宽度的一半的矩形

### ISSUE THREAD

**Issue by limengke123** [limengke123/my-note#11]
掘金上看到的,感觉可能会用得到,这里记录下:

```html
<div class="box">
  <div class="scale">
    <div class="item">
      16:9
    </div>
  </div>
</div>
```

```css
.box {
  width: 80%;
}

.scale {
  width: 100%;
  padding-bottom: 56.25%;
  height: 0;
  position: relative;
}

.item {
  width: 100%;
  height: 100%;
  background-color: aquamarine;
  position: absolute;
}
```

box是外层容器,scale是真正需要的盒子,内容写在item里面。

几个点需要注意下：height设置为0，高度通过padding-bottom来撑开，同时自容器设置为绝对定位强制充满sacle容器。
